### ISSUE TITLE
[roq-fix-bridge] Support FundsUpdate

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#109]
Funds require special subscription patterns. For the FIX Bridge this is achieved by subscribing without gateway/exchange like this

```toml
[symbols]
  regex=["USD.*", "BNB"]  # used to subscribe funds

  [symbols.bitmex]
  regex=["XBTUSD", "XBT.*"]

  [symbols.deribit]
  regex=".*"

  [symbols.ftx]
  regex=".*"

...
```
