### ISSUE TITLE
[roq-ftx] Config file should separate account alias from real name

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#185]
A new account field, `external_name` has been added

```toml
[accounts]                                                                                                                 
                                                                                                                        
  [accounts.A1]                                                                                                         
  master = true                                                                                                         
  sub_account = false                                                                                                   
  external_name = "YOUR_FTX_SUBACCOUNT_NAME_GOES_HERE"  # only if sub_account is true                                        
  login = "YOUR_FTX_API_KEY_GOES_HERE"                                                                                  
  secret = "YOUR_FTX_SECRET_GOES_HERE"                                                                                  
  symbols = [ ".*" ]  
```

> It was previously required to name the alias exactly like the real sub-account name used on FTX. Although no longer required, this is still an option for backwards compatibility.

> The reason for naming the field `external_name` is to be consistent with other API structures using `external_account` to refer to non-alias names.
