### ISSUE TITLE
[roq-api] Conda packaging should pin versions to match x.x.x

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#189]
This was noticed when trying to install an older version of the software.

The issue relates to the build section of `meta.yaml`

```yaml
build:
  run_exports:
    strong:
      - {{ pin_subpackage('roq-api', max_pin='x.x') }}
```

Pinning should use `'x.x.x'` instead of `'x.x'`.
