### ISSUE TITLE
[roq-server] Rate limiter should publish alerts using high/low water marks

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#251]

**Comment by thraneh** [comment]
Using high/low water mark is optional and can be enabled by using the `high_water_mark` and `low_water_mark` fields when configuring rate limiters in the gateway config.
For example

```toml
[rate_limits]

  [rate_limits.global]
  type = "ORDER_ACTION"
  aggregate = true
  request_limit = 50
  monitor_period = "120s"
  ban_period = "5m"
  high_water_mark = 40
  low_water_mark = 25
```

The `RateLimitTrigger` event has two new added fields: `buffer_capacity` and `remaining_requests`.

As before, when a rate limiter has been triggered, an event will be published now including `buffer_capacity == BufferCapacity::FULL` and `remaining_requests == 0`.

In addition, an event can be published when the rate limiter gets near the trigger. The event will include `buffer_capacity == BufferCapacity::HIGH_WATER_MARK` and `remaining_requests == (request_limit - high_water_mark)`. This event can only be triggered by a new order action.

The low water mark can only be triggered after the rate limiter has detected `HIGH_WATER_MARK` or `FULL`. The event will include `buffer_capacity == BufferCapacity::LOW_WATER_MARK` and `remaining_requests == (request_limit - low_water_mark)`. This event will normally be triggered by a timer.

Finally, when configured, the following must hold true: `0 < low_water_mark < high_water_mark < request_limit`.
