### ISSUE TITLE
[roq-binance] Support "cancelRestrictions"

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#328]
Binance's cancel-order request has a special field named "cancelRestrictions".

This is non-standard. Not found in FIX. Not seen on other major financial exchanges.

The question is how Roq's API can support it.

**Comment by thraneh** [comment]
The first step is to have Roq's `CancelOrder` support `request_template`. That's done with

* #329 

Next step is to add gateway support for templates. This has been implemented by having `roq-server` help with parsing templates from the TOML config. The structure must look like this

```toml
[templates]

  [templates.cancel_order]

    [templates.cancel_order.ON]
    cancel_restrictions = "ONLY_NEW"

    [templates.cancel_order.OPF]
    cancel_restrictions = "ONLY_PARTIALLY_FILLED" 
```

* First level must be `templates`
* Second level must be one of `create_order`, `modify_order` and `cancel_order`
* Third level must be a user-defined label (to be used with the `request_template` parameter from C++, see below)
* Parsing of the final table of key-value pairs is gateway specific

The `roq-binance` gateway supports the parsing of `cancel_restrictions` as per a pre-configured enum list.

Finally, the request can now look like this

```c++
auto cancel_order = CancelOrder{
  // ...
  .request_template = "OPF",  // note! this label must exist in the gateway TOML config
  // ...
};
```
