### ISSUE TITLE
[roq-server] Secrets file should support by-name

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#385]
It should be possible to define all secrets in a single file, e.g.

```toml
[deribit-1]
A1 = "some_secret"

[deribit-2]
A1 = "another_secret"
```

The old format is still supported, e.g.

```toml
A1 = "some_secret"
```
