### ISSUE TITLE
[roq-fix-bridge] Config file may specify what "zero" actually means (when responding to MD snapshot request)

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#62]
This config

```toml
[statistics]

  [statistics.FUNDING_RATE]
  fix_md_entry_type="PRIOR_SETTLE_PRICE"

  [statistics.PRE_SETTLEMENT_PRICE]
  fix_md_entry_type="SETTLEMENT_PRICE"
  default_value=-1.23
```

There is a user-defined "zero" value of -1.23 (double) for `PRE_SETTLEMENT_PRICE`. This value will be used to populate FIX snapshot request if and only if there is no snapshot available for this statistics type.

The default value, if not specified, is always 0.0 (double). This is therefore the case for the `FUNDING_RATE` config.

Finally, these values are only parsed and used if the `--init_missing_md_entry_type_to_zero` command-line flag is true.
