### ISSUE TITLE
[roq-server] User permissions were not being correctly validated

### ISSUE THREAD

**Issue by thraneh** [roq-trading/roq-issues#9]
### Background

Gateway config files typically look like this

```toml
[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "XBTUSD" ]
```

> For each user there is an **opt-in** selection of accounts and symbols.

The user is not allowed to trade the account/symbol if not explicitly listed and an `Error::NOT_AUTHORIZED` is generated if attempted.

### Issue

The library did not validate symbols.

### Changes

* Both `accounts` and `symbols` can now be a regex or list of regex'.
* Regex matching for accounts is performed at start-up.
* Regex matching for symbols is done at run-time, but the result (true/false) is cached so pattern matching only has to be done once.
